---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 7
    labels:
      - kind/dependencies
      - bot
    schedule:
      interval: daily
